# Use the official lightweight Python image
FROM python:3.11-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the shared requirements.txt from the parent directory
# (Jenkins will run the build from the /backend root)
COPY ../requirements.txt .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the main.py file from the current service folder into the container
COPY main.py .

# Expose the port FastAPI will run on
EXPOSE 80

# Command to run the application
CMD ["uvicorn", "main:app", "host", "0.0.0.0", "port", "80"]